# Generated by Django 5.0.3 on 2024-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historic",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
