# Generated by Django 5.0.3 on 2024-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0109_alter_variable_value_class"),
        ("sse", "0002_historic_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="historic",
            name="status_variables",
            field=models.ManyToManyField(
                related_name="status_variables", to="pyscada.variable"
            ),
        ),
        migrations.AddField(
            model_name="historic",
            name="variable_properties",
            field=models.ManyToManyField(to="pyscada.variableproperty"),
        ),
    ]
