# Generated by Django 5.1.4 on 2025-01-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sse", "0003_historic_status_variables_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSE",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
