# Generated by Django 5.1.4 on 2025-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sse", "0004_sse"),
    ]

    operations = [
        migrations.AddField(
            model_name="historic",
            name="busy",
            field=models.BooleanField(default=False),
        ),
    ]
